# Generated by Django 5.2.8 on 2025-12-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgresql', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=36),
        ),
    ]
