# Generated by Django 5.2.8 on 2025-11-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('expiration_date', models.DateField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
