# Generated by Django 5.2.8 on 2025-11-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgresql', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='name',
            field=models.CharField(default='', max_length=36, unique=True),
        ),
    ]
