# Generated by Django 5.2.8 on 2025-12-02 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgresql', '0003_stockmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmodel',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='postgresql.productmodel'),
        ),
    ]
